name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: '1.10.4'
              otp: '23.0.4'
          - pair:
              elixir: '1.11.4'
              otp: '23.3.4.17'
          - pair:
              elixir: '1.12.3'
              otp: '24.0.6'
          - pair:
              elixir: '1.13.4'
              otp: '24.3.4.4'
          - pair:
              elixir: '1.14.0'
              otp: '25.0.4'
          - pair:
              elixir: '1.14.3'
              otp: '25.2.3'
            lint: lint
    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}

      - name: Install Dependencies
        run: mix deps.get --only test

      - run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - run: mix deps.get && mix deps.unlock --check-unused
        if: ${{ matrix.lint }}

      - run: mix deps.compile

      - run: mix compile --warnings-as-errors
        if: ${{ matrix.lint }}

      - run: mix credo
        if: ${{ matrix.lint }}

      - run: mix test
